name: Copy Files to Root

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to root
        run: |
          cp -r src/* .
        working-directory: ${{ github.workspace }}
