# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Custom Action: Move source files to root folder on GitHub Pages

      # Remove all root files and folders (except for the 'src' folder)
      - name: Clean Root Directory
        run: |
          shopt -s extglob
          rm -rf !(src)
        shell: bash

      # Move all files from the 'src' folder to the root folder
      - name: Move files from 'src' to root
        run: mv src/* .
        working-directory: ${{ github.workspace }}

      # Remove the 'src' folder
      - name: Remove 'src' folder
        run: rm -rf src

      # Custom Action: Minify JavaScript files
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install UglifyJS
        run: npm install -g uglify-es

      - name: Minify JavaScript files
        run: |
          find . -type f -name "*.js" -exec uglifyjs {} -o {}.min \; -exec mv {}.min {} \;
        working-directory: ${{ github.workspace }}

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
